import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React, {FunctionComponent, HTMLAttributes, PropsWithChildren} from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


type RootLayoutProps = PropsWithChildren<HTMLAttributes<HTMLDivElement>>

const RootLayout: FunctionComponent<RootLayoutProps> = ({children}) => {
  return (
    <html lang="fr">
      <body className={inter.className}>{children}</body>
    </html>
  )
}


export default RootLayout